version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: basket_app_nginx
    restart: always
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      basket-app:
        aliases:
          - basket-app.local
        ipv4_address: 172.20.29.29

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: basket_app_php
    user: ${CURRENT_USER}
    volumes:
      - ../:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - basket-app

  mysql_test:
    image: mariadb:latest
    command: --authentication_policy=mysql_native_password
    container_name: basket_app_mysql_test
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      SERVICE_TAGS: test
      SERVICE_NAME: mysql_test
    networks:
      - basket-app

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: basket_app_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - basket-app

  composer:
    image: composer:latest
    container_name: basket_app_composer
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - basket-app

  npm:
    image: node:latest
    container_name: basket_app_npm
    volumes:
      - ../:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: basket_app_artisan
    volumes:
      - ../:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - basket-app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: basket_app_phpmyadmin
    depends_on:
      - mysql
    ports:
      - "81:80"
    environment:
      PMA_HOST: mysql
    networks:
      - basket-app

  redis:
    image: redis:alpine
    container_name: basket_app_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - basket-app

volumes:
  mysql-data:
    driver: local

networks:
  basket-app:
    driver: bridge
    name: basket-application
    ipam:
      config:
        - subnet: 172.20.10.0/16
