name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build project images
      run: make up
    - name: Install composer
      run: make composer install
    - name: Migrate migrations 
      run: make migrations_migrate
    - name: run tests
      run: make run_tests
